"""add critical care module

Revision ID: 31badf7d1252
Revises: 75ffa3939d01
Create Date: 2026-08-20 20:40:21.671020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31badf7d1252'
down_revision: Union[str, None] = '75ffa3939d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critical_care_admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.Enum('ICU', 'CCU', 'NICU', name='criticalcareunit'), nullable=False),
    sa.Column('admission_reason', sa.Text(), nullable=False),
    sa.Column('apache_ii_score', sa.Integer(), nullable=True),
    sa.Column('code_status', sa.Enum('FULL_CODE', 'DNR', 'DNI', 'COMFORT_CARE', name='codestatus'), nullable=True),
    sa.Column('on_ventilator', sa.Boolean(), nullable=True),
    sa.Column('central_line', sa.Boolean(), nullable=True),
    sa.Column('central_line_site', sa.String(length=100), nullable=True),
    sa.Column('urinary_catheter', sa.Boolean(), nullable=True),
    sa.Column('arterial_line', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('stepped_down_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('step_down_notes', sa.Text(), nullable=True),
    sa.Column('admitted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critical_care_admissions_id'), 'critical_care_admissions', ['id'], unique=False)
    op.create_index(op.f('ix_critical_care_admissions_ipd_admission_id'), 'critical_care_admissions', ['ipd_admission_id'], unique=False)
    op.create_table('critical_care_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('critical_care_admission_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ventilator_mode', sa.String(length=50), nullable=True),
    sa.Column('fio2_percent', sa.Float(), nullable=True),
    sa.Column('peep', sa.Float(), nullable=True),
    sa.Column('tidal_volume_ml', sa.Float(), nullable=True),
    sa.Column('inotropes', sa.Text(), nullable=True),
    sa.Column('sedation_score', sa.Integer(), nullable=True),
    sa.Column('gcs_score', sa.Integer(), nullable=True),
    sa.Column('urine_output_ml', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['critical_care_admission_id'], ['critical_care_admissions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critical_care_rounds_id'), 'critical_care_rounds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_critical_care_rounds_id'), table_name='critical_care_rounds')
    op.drop_table('critical_care_rounds')
    op.drop_index(op.f('ix_critical_care_admissions_ipd_admission_id'), table_name='critical_care_admissions')
    op.drop_index(op.f('ix_critical_care_admissions_id'), table_name='critical_care_admissions')
    op.drop_table('critical_care_admissions')
    # ### end Alembic commands ###
