"""add emergency module

Revision ID: 75ffa3939d01
Revises: fe83af44112c
Create Date: 2026-08-20 05:55:25.158230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ffa3939d01'
down_revision: Union[str, None] = 'fe83af44112c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('er_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('er_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('arrival_mode', sa.Enum('WALK_IN', 'AMBULANCE', 'POLICE', 'REFERRED', 'BROUGHT_DEAD', name='arrivalmode'), nullable=True),
    sa.Column('brought_by', sa.String(length=200), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_TRIAGE', 'IN_TREATMENT', 'ADMITTED', 'DISCHARGED', 'REFERRED_OUT', 'DECEASED', 'LEFT_WITHOUT_TREATMENT', name='ervisitstatus'), nullable=True),
    sa.Column('is_mlc', sa.Boolean(), nullable=True),
    sa.Column('mlc_number', sa.String(length=30), nullable=True),
    sa.Column('is_trauma', sa.Boolean(), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('police_informed', sa.Boolean(), nullable=True),
    sa.Column('police_station', sa.String(length=200), nullable=True),
    sa.Column('fir_number', sa.String(length=50), nullable=True),
    sa.Column('attending_doctor_id', sa.Integer(), nullable=True),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('discharge_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_er_visits_er_number'), 'er_visits', ['er_number'], unique=True)
    op.create_index(op.f('ix_er_visits_id'), 'er_visits', ['id'], unique=False)
    op.create_table('er_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('er_visit_id', sa.Integer(), nullable=False),
    sa.Column('treatment_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('treatment_given', sa.Text(), nullable=False),
    sa.Column('medication_given', sa.Text(), nullable=True),
    sa.Column('procedure_performed', sa.Text(), nullable=True),
    sa.Column('given_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['er_visit_id'], ['er_visits.id'], ),
    sa.ForeignKeyConstraint(['given_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_er_treatments_id'), 'er_treatments', ['id'], unique=False)
    op.create_table('er_triage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('er_visit_id', sa.Integer(), nullable=False),
    sa.Column('triage_level', sa.Enum('LEVEL_1_RESUSCITATION', 'LEVEL_2_EMERGENT', 'LEVEL_3_URGENT', 'LEVEL_4_LESS_URGENT', 'LEVEL_5_NON_URGENT', name='triagelevel'), nullable=False),
    sa.Column('triage_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('triaged_by', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('glasgow_coma_scale', sa.Integer(), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['er_visit_id'], ['er_visits.id'], ),
    sa.ForeignKeyConstraint(['triaged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_er_triage_id'), 'er_triage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_er_triage_id'), table_name='er_triage')
    op.drop_table('er_triage')
    op.drop_index(op.f('ix_er_treatments_id'), table_name='er_treatments')
    op.drop_table('er_treatments')
    op.drop_index(op.f('ix_er_visits_id'), table_name='er_visits')
    op.drop_index(op.f('ix_er_visits_er_number'), table_name='er_visits')
    op.drop_table('er_visits')
    # ### end Alembic commands ###
