"""add ambulance module

Revision ID: 854ef83cea06
Revises: 31badf7d1252
Create Date: 2026-08-21 02:12:34.769553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854ef83cea06'
down_revision: Union[str, None] = '31badf7d1252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BASIC_LIFE_SUPPORT', 'ADVANCED_LIFE_SUPPORT', 'PATIENT_TRANSPORT', 'NEONATAL', name='vehicletype'), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'MAINTENANCE', 'OUT_OF_SERVICE', name='vehiclestatus'), nullable=True),
    sa.Column('make_model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('equipment_notes', sa.Text(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulance_vehicles_id'), 'ambulance_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_ambulance_vehicles_vehicle_number'), 'ambulance_vehicles', ['vehicle_number'], unique=True)
    op.create_table('ambulance_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_ambulance_drivers_id'), 'ambulance_drivers', ['id'], unique=False)
    op.create_table('ambulance_fuel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('filled_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['filled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ambulance_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulance_fuel_logs_id'), 'ambulance_fuel_logs', ['id'], unique=False)
    op.create_table('ambulance_maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_by', sa.String(length=200), nullable=True),
    sa.Column('logged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ambulance_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulance_maintenance_logs_id'), 'ambulance_maintenance_logs', ['id'], unique=False)
    op.create_table('ambulance_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('er_visit_id', sa.Integer(), nullable=True),
    sa.Column('trip_type', sa.Enum('EMERGENCY_PICKUP', 'HOSPITAL_TRANSFER', 'DISCHARGE_TRANSPORT', 'OTHER', name='triptype'), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'DISPATCHED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=True),
    sa.Column('pickup_location', sa.String(length=300), nullable=False),
    sa.Column('drop_location', sa.String(length=300), nullable=True),
    sa.Column('caller_name', sa.String(length=200), nullable=True),
    sa.Column('caller_phone', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['ambulance_drivers.id'], ),
    sa.ForeignKeyConstraint(['er_visit_id'], ['er_visits.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ambulance_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulance_trips_id'), 'ambulance_trips', ['id'], unique=False)
    op.create_index(op.f('ix_ambulance_trips_trip_number'), 'ambulance_trips', ['trip_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ambulance_trips_trip_number'), table_name='ambulance_trips')
    op.drop_index(op.f('ix_ambulance_trips_id'), table_name='ambulance_trips')
    op.drop_table('ambulance_trips')
    op.drop_index(op.f('ix_ambulance_maintenance_logs_id'), table_name='ambulance_maintenance_logs')
    op.drop_table('ambulance_maintenance_logs')
    op.drop_index(op.f('ix_ambulance_fuel_logs_id'), table_name='ambulance_fuel_logs')
    op.drop_table('ambulance_fuel_logs')
    op.drop_index(op.f('ix_ambulance_drivers_id'), table_name='ambulance_drivers')
    op.drop_table('ambulance_drivers')
    op.drop_index(op.f('ix_ambulance_vehicles_vehicle_number'), table_name='ambulance_vehicles')
    op.drop_index(op.f('ix_ambulance_vehicles_id'), table_name='ambulance_vehicles')
    op.drop_table('ambulance_vehicles')
    # ### end Alembic commands ###
