"""add group4 clinical depth and portals modules

Revision ID: g4clinicaldepth01
Revises: 854ef83cea06
Create Date: 2026-08-24 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g4clinicaldepth01'
down_revision: Union[str, None] = '854ef83cea06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Group 4 (Clinical Depth + Portals) tables — hand-written from the
    # ### SQLAlchemy models since this environment has no network access to
    # ### run 'alembic revision --autogenerate' against a live DB. Column
    # ### definitions were generated by parsing models/*.py directly (see
    # ### GROUP4_ROADMAP.md), not typed by hand, to avoid transcription drift.
    # ### NOT YET RUN against a live database in this environment — review
    # ### and test on a staging DB before applying to production.
    op.create_table('order_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('clinical_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ordering_doctor_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('LAB', 'RADIOLOGY', 'MEDICATION', 'NURSING', 'PROCEDURE', 'DIET', 'CONSULTATION', 'BLOOD_BANK', 'OTHER', name='ordertype'), nullable=False),
    sa.Column('order_set_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'STAT', name='orderpriority'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ORDERED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='orderstatus'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=True),
    sa.Column('fulfilled_module', sa.String(length=50), nullable=True),
    sa.Column('fulfilled_ref_id', sa.Integer(), nullable=True),
    sa.Column('safety_check_result', sa.JSON(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['ordering_doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['order_set_id'], ['order_sets.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('clinical_order_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['order_id'], ['clinical_orders.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('consent_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('requires_witness', sa.Boolean(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('patient_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'REFUSED', 'WITHDRAWN', 'EXPIRED', name='consentstatus'), nullable=True),
    sa.Column('consented_by_name', sa.String(length=200), nullable=True),
    sa.Column('relationship_to_patient', sa.String(length=100), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('witness_name', sa.String(length=200), nullable=True),
    sa.Column('explained_by', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['consent_templates.id'], ),
    sa.ForeignKeyConstraint(['explained_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('clinical_pathway_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('patient_care_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DISCONTINUED', name='pathwaystatus'), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('target_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['clinical_pathway_templates.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('care_plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'MISSED', 'SKIPPED', name='taskstatus'), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['care_plan_id'], ['patient_care_plans.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('pre_anesthesia_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('surgery_id', sa.Integer(), nullable=False),
    sa.Column('anesthesiologist_id', sa.Integer(), nullable=False),
    sa.Column('asa_grade', sa.Enum('ASA_I', 'ASA_II', 'ASA_III', 'ASA_IV', 'ASA_V', 'ASA_VI', name='asagrade'), nullable=True),
    sa.Column('airway_assessment', sa.Text(), nullable=True),
    sa.Column('fasting_status', sa.Enum('CONFIRMED_NPO', 'NOT_CONFIRMED', 'EMERGENCY_FULL_STOMACH', name='fastingstatus'), nullable=True),
    sa.Column('comorbidities_reviewed', sa.Boolean(), nullable=True),
    sa.Column('allergies_reviewed', sa.Boolean(), nullable=True),
    sa.Column('previous_anesthesia_issues', sa.Text(), nullable=True),
    sa.Column('planned_technique', sa.String(length=100), nullable=True),
    sa.Column('investigations_reviewed', sa.Text(), nullable=True),
    sa.Column('fitness_for_anesthesia', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.id'], ),
    sa.ForeignKeyConstraint(['anesthesiologist_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('anesthesia_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surgery_id', sa.Integer(), nullable=False, unique=True),
    sa.Column('anesthesiologist_id', sa.Integer(), nullable=False),
    sa.Column('technique_used', sa.String(length=100), nullable=True),
    sa.Column('induction_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intubation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extubation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drugs_administered', sa.JSON(), nullable=True),
    sa.Column('fluids_administered', sa.JSON(), nullable=True),
    sa.Column('blood_products_used', sa.JSON(), nullable=True),
    sa.Column('intraop_events', sa.Text(), nullable=True),
    sa.Column('total_blood_loss_ml', sa.Integer(), nullable=True),
    sa.Column('total_urine_output_ml', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.id'], ),
    sa.ForeignKeyConstraint(['anesthesiologist_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('anesthesia_vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anesthesia_record_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('etco2', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['anesthesia_record_id'], ['anesthesia_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('recovery_room_stays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surgery_id', sa.Integer(), nullable=False, unique=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('admitted_by', sa.Integer(), nullable=True),
    sa.Column('aldrete_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_RECOVERY', 'READY_FOR_DISCHARGE', 'DISCHARGED_TO_WARD', 'DISCHARGED_TO_ICU', name='recoverystatus'), nullable=True),
    sa.Column('pain_score_on_arrival', sa.Integer(), nullable=True),
    sa.Column('nausea_vomiting', sa.Boolean(), nullable=True),
    sa.Column('airway_patent', sa.Boolean(), nullable=True),
    sa.Column('bleeding_at_site', sa.Boolean(), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_by', sa.Integer(), nullable=True),
    sa.Column('discharge_destination', sa.String(length=100), nullable=True),
    sa.Column('discharge_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['admitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discharged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('recovery_room_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_stay_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('consciousness_level', sa.String(length=50), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_stay_id'], ['recovery_room_stays.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('physiotherapy_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=True),
    sa.Column('referring_doctor_id', sa.Integer(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=300), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('plan_details', sa.Text(), nullable=True),
    sa.Column('frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('total_sessions_planned', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DISCONTINUED', name='rehabplanstatus'), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.ForeignKeyConstraint(['referring_doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('physiotherapy_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'MISSED', 'CANCELLED', name='sessionstatus'), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('activities_performed', sa.Text(), nullable=True),
    sa.Column('pain_score_before', sa.Integer(), nullable=True),
    sa.Column('pain_score_after', sa.Integer(), nullable=True),
    sa.Column('functional_improvement_notes', sa.Text(), nullable=True),
    sa.Column('patient_tolerance', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['plan_id'], ['physiotherapy_plans.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('pain_management_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=True),
    sa.Column('managing_doctor_id', sa.Integer(), nullable=False),
    sa.Column('pain_type', sa.Enum('ACUTE', 'CHRONIC', 'CANCER_RELATED', 'POST_SURGICAL', 'NEUROPATHIC', name='paintype'), nullable=False),
    sa.Column('pain_location', sa.String(length=200), nullable=True),
    sa.Column('baseline_pain_score', sa.Integer(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('target_pain_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.ForeignKeyConstraint(['managing_doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('pain_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=False),
    sa.Column('pain_character', sa.String(length=100), nullable=True),
    sa.Column('interventions_given', sa.JSON(), nullable=True),
    sa.Column('response_after_intervention', sa.String(length=100), nullable=True),
    sa.Column('side_effects_noted', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['pain_management_plans.id'], ),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('palliative_care_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ipd_admission_id', sa.Integer(), nullable=True),
    sa.Column('primary_doctor_id', sa.Integer(), nullable=False),
    sa.Column('primary_diagnosis', sa.String(length=300), nullable=False),
    sa.Column('care_setting', sa.Enum('INPATIENT', 'HOME_BASED', 'OUTPATIENT_CLINIC', name='caresetting'), nullable=True),
    sa.Column('goals_of_care', sa.Text(), nullable=True),
    sa.Column('code_status', sa.String(length=50), nullable=True),
    sa.Column('primary_caregiver_name', sa.String(length=200), nullable=True),
    sa.Column('primary_caregiver_contact', sa.String(length=20), nullable=True),
    sa.Column('psychosocial_support_needed', sa.Boolean(), nullable=True),
    sa.Column('spiritual_support_needed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['ipd_admission_id'], ['ipd_admissions.id'], ),
    sa.ForeignKeyConstraint(['primary_doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('palliative_symptom_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('symptom_scores', sa.JSON(), nullable=True),
    sa.Column('interventions_given', sa.Text(), nullable=True),
    sa.Column('family_meeting_held', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['palliative_care_plans.id'], ),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('patient_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, unique=True),
    sa.Column('phone', sa.String(length=20), nullable=False, unique=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('patient_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('DOCTOR', 'NURSING', 'FACILITY', 'BILLING', 'FOOD', 'OVERALL', name='feedbackcategory'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('patient_grievances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department_concerned', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='grievancestatus'), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('virtual_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='consultationstatus'), nullable=True),
    sa.Column('meeting_provider', sa.String(length=50), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('meeting_id_external', sa.String(length=200), nullable=True),
    sa.Column('is_second_opinion', sa.Boolean(), nullable=True),
    sa.Column('referring_doctor_id', sa.Integer(), nullable=True),
    sa.Column('reason_for_consult', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('consultation_notes', sa.Text(), nullable=True),
    sa.Column('prescription_issued', sa.Boolean(), nullable=True),
    sa.Column('follow_up_advised', sa.Boolean(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['referring_doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('health_checkup_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('booked_date', sa.Date(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'SAMPLES_COLLECTED', 'IN_PROGRESS', 'REPORT_READY', 'COMPLETED', 'CANCELLED', name='checkupbookingstatus'), nullable=True),
    sa.Column('opd_visit_id', sa.Integer(), nullable=True),
    sa.Column('lab_order_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['billing_packages.id'], ),
    sa.ForeignKeyConstraint(['opd_visit_id'], ['opd_visits.id'], ),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('linked_patient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relation_type', sa.Enum('SPOUSE', 'CHILD', 'PARENT', 'SIBLING', 'GUARDIAN', 'CAREGIVER', 'OTHER', name='relationtype'), nullable=False),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=True),
    sa.Column('is_authorized_proxy', sa.Boolean(), nullable=True),
    sa.Column('proxy_scope_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['linked_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('patient_category_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, unique=True),
    sa.Column('category', sa.Enum('DOMESTIC', 'INTERNATIONAL', 'MEDICAL_TOURISM', 'CORPORATE', name='patientcategory'), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('visa_number', sa.String(length=50), nullable=True),
    sa.Column('visa_expiry', sa.Date(), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('interpreter_required', sa.Boolean(), nullable=True),
    sa.Column('facilitator_agency', sa.String(length=200), nullable=True),
    sa.Column('corporate_employer_name', sa.String(length=200), nullable=True),
    sa.Column('corporate_employee_id', sa.String(length=100), nullable=True),
    sa.Column('corporate_scheme_name', sa.String(length=200), nullable=True),
    sa.Column('corporate_tpa_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['corporate_tpa_id'], ['insurance_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('cds_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.Enum('DRUG_INTERACTION', 'DUPLICATE_THERAPY', 'MAX_DOSE', 'AGE_RESTRICTION', 'GENERAL_ALERT', name='cdsruletype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='cdsseverity'), nullable=True),
    sa.Column('trigger_keyword', sa.String(length=200), nullable=False),
    sa.Column('conflict_keyword', sa.String(length=200), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('cds_alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinical_order_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='cdsseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('was_overridden', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.ForeignKeyConstraint(['rule_id'], ['cds_rules.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['clinical_order_id'], ['clinical_orders.id'], ),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('cds_alert_logs')
    op.drop_table('cds_rules')
    op.drop_table('patient_category_profiles')
    op.drop_table('family_members')
    op.drop_table('health_checkup_bookings')
    op.drop_table('virtual_consultations')
    op.drop_table('patient_grievances')
    op.drop_table('patient_feedback')
    op.drop_table('patient_accounts')
    op.drop_table('palliative_symptom_assessments')
    op.drop_table('palliative_care_plans')
    op.drop_table('pain_assessments')
    op.drop_table('pain_management_plans')
    op.drop_table('physiotherapy_sessions')
    op.drop_table('physiotherapy_plans')
    op.drop_table('recovery_room_observations')
    op.drop_table('recovery_room_stays')
    op.drop_table('anesthesia_vitals')
    op.drop_table('anesthesia_records')
    op.drop_table('pre_anesthesia_assessments')
    op.drop_table('care_plan_tasks')
    op.drop_table('patient_care_plans')
    op.drop_table('clinical_pathway_templates')
    op.drop_table('form_submissions')
    op.drop_table('form_templates')
    op.drop_table('patient_consents')
    op.drop_table('consent_templates')
    op.drop_table('clinical_order_notes')
    op.drop_table('clinical_orders')
    op.drop_table('order_sets')
